### PR TITLE
[WIP] Replace gmaps by osm

### PR DESCRIPTION
**Pull request by RoPP**
This PR propose to switch from google maps to leaflet.
It need some more cleaning but it should be enough to play with it. Let me know if you're interested.

Ref #366

### CODE REVIEW

**Comment by mohierf** [comment]
Thanks! Very interesting !

I had a look on OSM several months ago ... but had not enough time to switch from Gmap to OSM :/P

I will a neat look to your PR

**Comment by mohierf** [comment]
Really nice !

image

To get it run properly I had to fix something in your PR : you introduced a space sign before the `{{mapId}}` in *_worldmap.tpl* ... as of it it raises Javascript errors!

**Comment by ddurieux** [comment]
Really cool ^^

**Comment by maethor** [comment]
This is really nice. Thanks @RoPP !

**Comment by mehdicopter** [comment]
That was me who asked back in the days to implement OSM :)

Thanks a lot !!!

**Pull request merged**
