### PR TITLE
CSS styling:

### PR DESCRIPTION
**Pull request by mohierf**
- some cleanings
- fix pagination element
- hide breadcrumb and top pagination on xs devices
- fix menu on xs devices

### CODE REVIEW

**Comment by mohierf** [comment]
The main modification is the menu on small devices:
image

**Comment by mohierf** [comment]
I rebased on the most recent develop branch. Should be merged now 😉

**Comment by maethor** [comment]
Still I am not sure I agree with what you did in this PR. I need to test it.

**Comment by mohierf** [comment]
The menu is completely corrupted on a smartphone screen ! Not even possible to use it ... I made it functional at least 😉

**Comment by maethor** [comment]
Hm. I disagree, it seems to work perfectly fine on my Nexus 5X with Chrome and my Iphone XS with Safari.

**Comment by mohierf** [comment]
iPad : 
image

Galaxy S5, :
image

**Note** the missing menu items after System and when I click on a menu item  (Groups and tags) it closes all the menu and do not navigate !

**Comment by maethor** [comment]
I see. Well, I will give it a chance then :)

**Comment by maethor** [comment]
OK, it will need updates because I don't agree with what it is doing. I often split my screen vertically with the browser on the left and a console on the right, so I don't want the search bar to disappear in this situation… That's very annoying.

Please don't touch at the search bar.

**Comment by maethor** [comment]
I reverted the commit.

**Comment by mohierf** [comment]
Ok. I understand what you experienced ... I will fix this medai query step ;)

**Pull request merged**
