### PR TITLE
For 638

### PR DESCRIPTION
**Pull request by mohierf**
@maethor: I did several commits, one for each item in the issue. If you prefer I will squash all the commits into one commit.

image

On a fresh page without any problem, I set this message:
image

This message is displayed if one is using the default search query (the one that makes real problems raise ;)) and no result is matching this query.

### CODE REVIEW

**Comment by maethor** [comment]
OK, thank you @mohierf!

**Comment by maethor** [comment]
I think I don't like the badge. It gets too much attention because, on most of web app, a badge in this area means a notification. This is not a notification.

What do you think @mohierf ?

**Comment by maethor** [comment]
More importantly, it doesn't work as it should on all window sizes.

**Comment by mohierf** [comment]
IMHO, the badge is a quite good solution. It means you have a problem to manage. If you fix, ack or downtime your problem, the badge will disappear 😉 

And yes, I just saw this morning that the top header ... I will fix this in a next PR

**Comment by maethor** [comment]
It really depends on the problem. Personally I have a lot of services not OK in the Low importance category. Some stuff I have to keep in mind, and eventually treat, like upgrades waiting to be applied, but nothing urgent. For me, important stuff begin at "Normal", or even "Important".

**Comment by mohierf** [comment]
@maethor: I understand and I think that a nice solution would be to define the minimum business impact for raising a problem. If a service is "NOT OK HARD" and its BI is enough important, then it is a problem ! Iwill submit a modification for this...

**Comment by maethor** [comment]
I think you can allow to configure the entire request, not just bp. Make it "bp>2" by default, please.

**Pull request merged**
