### PR TITLE
Mongodb submodules

### PR DESCRIPTION
**Pull request by mohierf**
Update mongodb sub-modules to manage correctly the DB connection if mongodb is not installed or running.

### CODE REVIEW

**Comment by mohierf** [comment]
This PR makes #332 obsolete because Web UI will be able to be used "comfortably" without any MongDB installed.

**Comment by maethor** [comment]
Can you explain your commit to me? I see that at the init you are trying to use the mongo database (with search and insert)… why are you doing that?

**Comment by mohierf** [comment]
To be sure that mongodb is installed and running, it is mandatory to : 
- create a MongoClient
- connect to a database
- fetch a collection
- read and write in the collection

 If you do not make all this stuff you cannot assume that mongodb is operational ... and you cannot declare the module as available ...

**Comment by maethor** [comment]
OK. Seems odd to me, but why not.

**Comment by mohierf** [comment]
Also seems odd to me! But pymongo is only a *driver* as some people say  on the Internet ... and, as of it, it is not its job to manage if mongodb is installed and running :/P

**Pull request merged**
