### PR TITLE
Add a copy-to-clipboard function for the problem server hostname

### PR DESCRIPTION
**Pull request by eherot**
I borrowed the icon from GitHub so we might want to change that part and also maybe change the shape of the icon which is a bit awkward looking right now but the basic functionality works.

### CODE REVIEW

**Comment by maethor** [comment]
Hi @eherot,

Can you give us a screenshot of the result?

Regardless of the code, I don't think this feature is worth adding a button on every line of a table which need to be as simple and clean as possible.

Thanks,

**Comment by mohierf** [comment]
I do agree with you @maethor

**Comment by eherot** [comment]
screen shot 2016-09-27 at 11 06 09 am

I modified the design slightly from what's in the pull request to remove the button frame. As you can see, though, at least in my experience thus far, it usually ends up being placed in space that otherwise goes unused because of the wrapping in the Service column.

The main reason I find this useful is that the text being a link makes selecting it kind of a pain. Having the button would definitely speed up the troubleshooting process for me.

**Comment by eherot** [comment]
I updated the PR to reflect what's in the screenshot.

**Comment by maethor** [comment]
Hm… It seems you are running a really old version of the Shinken WebUI, because it doesn't look like that anymore.

**Comment by eherot** [comment]
Oops. I didn't even realize I had that pinned. Here it is in the new UI:
screen shot 2016-09-29 at 1 50 18 pm

**Comment by eherot** [comment]
Although in the new design this might be a better place for it:
screen shot 2016-09-29 at 2 07 21 pm

**Comment by maethor** [comment]
Alias is not a clickable field, so you can copy paste this text normally. You don't need a button.

I'm sorry, I will not merge this PR. We need to keep the UI as simple as possible.

**Pull request closed without merging**
