### PR TITLE
Clean element details view:

### LINKED ISSUE #682: No defined check command raises an exception
When no check command is defined for an host, ane exception is raised on the element view page. It is allowed to avoid defining a check command ... this means the host is always considered as UP.

### PR DESCRIPTION
**Pull request by mohierf**
- exception if no check comand is defined (closes #682)
- function to get a configuration parameter
- clean comments and downtimes tabs

### CODE REVIEW

**Comment by maethor** [comment]
@mohierf I'm ok with this PR.  You can resolv the conflit and merge it yourself.

**Comment by mohierf** [comment]
@maethor: ok. I will rebase on develop, fix the conflict and merge into develop

**Comment by maethor** [comment]
I get an error 500 in elt view. I revert this PR. Sorry.

Please be careful. I understand you want to improve the webui but I really don't have time to play with that kind of stuff right now…

**Comment by mohierf** [comment]
Which 500 Error ? A screen capture please ...

**Comment by maethor** [comment]
I do not have detail, just error 500.

I tryied to enable debug mode to have stack trace but it does not seem to work.

**Comment by mohierf** [comment]
For debug mode, you must set the SHINKEN_UI_DEBUG environment variable ... in /etc/init.d/shinken:
```
export SHINKEN_UI_DEBUG=1
```

**Comment by maethor** [comment]
Oh, OK. I will test it tomorrow morning.

Le 18/12/17 23:28, Frédéric MOHIER a écrit :
> For debug mode, you must set the SHINKEN_UI_DEBUG environment variable ... in /etc/init.d/shinken:
> ```
> export SHINKEN_UI_DEBUG=1
> ```
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/shinken-monitoring/mod-webui/pull/683#issuecomment-448123044

-- 
Guillaume Subiron 
  Mail - maethor@subiron.org
   GPG - 5BC2 EADB
 MSTDN - @maethor@mstdn.fr
   IRC - maethor@(freenode|geeknode)

**Comment by maethor** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 656, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3615, in wrapper
    result = func(*args, **kwargs)
  File "/var/lib/shinken/modules/webui2/plugins/eltdetail/eltdetail.py", line 81, in show_service
    configintervallength = vars(configs[0])['interval_length']
TypeError: vars() argument must have __dict__ attribute
```

**Comment by maethor** [comment]
OK, my mistake. It is working fine.

**Pull request merged**
