### PR TITLE
Fix widgets selector layout

### PR DESCRIPTION
**Pull request by mohierf**

### CODE REVIEW

**Comment by maethor** [comment]
Still the same display bug.

**Comment by mohierf** [comment]
@maethor : I just restarted from the most recent develop ad I have no display bug: 

image

Which browser ? Cache is cleant ?

**Comment by maethor** [comment]
Chromium, cache is clean. I will try to find errors in the console.

**Comment by mohierf** [comment]
I will also give a try with Chromium

**Comment by mohierf** [comment]
Just installed the most recent Chromium on my Ubuntu 18, no problems for me:
image

**Pull request merged**
