### PR TITLE
fix UTC downtime

### PR DESCRIPTION
**Pull request by andyxning**
I have write a pull request for the problem #105. I have test it in the version downloaded through __shinken install webui__, and i think it should be RELEASE1.0. So, i think if you accept this PR, it can be merged to the version in shinken.io.

### CODE REVIEW

**Comment by mohierf** [comment]
Please look in BS3 branch ... these modifications have been backported.

**Comment by andyxning** [comment]
Ok, then i think you can close this PR. :)

**Comment by mohierf** [comment]
Did you checked it is ok ? I hope I did not forgot anything ...

**Comment by andyxning** [comment]
I have checked that the code in `module/module.py` is ok, however, i am not familiar with JS  so i can not tell the difference with `localtime` and `gmtime` in JS. But the difference between my PR and the code in `module/plugins/forms/views/form_downtime.tpl` is that PR uses `localtime` and the code in BS3 uses `gmtime`. I think `gmtime` is the UTC time which will not use the timezone setted by `time.tzset()`.

```
%import time
%now = time.gmtime(int(time.time()))
%nxt = time.gmtime(int(time.time()) + 3600*2)
```
should be changed to 
```
%import time
%now = time.localtime(int(time.time()))
%nxt = time.localtime(int(time.time()) + 3600*2)
```

**Comment by mohierf** [comment]
In the BS3 branch, you do not have this code: mod-webui/module/plugins/forms/views/form_downtime.tpl

 It uses the Javascript library moment.js that should deal correctly with local time. I tested and got consistent downtimes ... should you confirm with a test in your configuration ?

**Comment by andyxning** [comment]
Sorry for my mistake. I have confirmed that the code using `gmtime` is in
the master branch.

I think if the `moment` will do the right job as `localtime`, then it is
Ok.

Good Job.

++++++
Ning Xie


2015-06-05 13:17 GMT+08:00 Frédéric MOHIER <notifications@github.com>:

**Comment by mohierf** [comment]
As of it, I close this PR. If someone should be interested in master branch we will reopen and merge ...

**Pull request closed without merging**
