### PR TITLE
Use the contact_name rather than alias in the external commands

### PR DESCRIPTION
**Pull request by mohierf**
Using the get_name() function for the name of the user in the external comands is not consistent ... Nagios / Shinken / Alignak expect the contact_name property and not the display_name nor alias one

### CODE REVIEW

**Comment by maethor** [comment]
Are you sure about this? I don't have time to review it properly, but if it breaks anything in my setup I will revert. And we use external commands a lot.

**Comment by mohierf** [comment]
@maethor : I am almost 99.99% sure that it will not beak anything,  but do not merge yet!

I tested with my Alignak and it is ok but I will make a test with Shinken and I will confirm to you 😉

**Comment by maethor** [comment]
OK. You can merge by yourself when you think this is fine. I'm ok with it.

**Comment by mohierf** [comment]
Ok. I will merge after my tests

**Comment by mohierf** [comment]
Confirmed! One must use the `contact_name` in some external comands because Shinken searches for an existing contact for some commands

**Pull request merged**
