### PR TITLE
Bs3 sb admin 2

### PR DESCRIPTION
**Pull request by maethor**
@mohierf this PR adds and uses Bootstrap theme sb-admin-2 for the layout.

There is s some regressions: I had to deactivate the typeahead and to remove the badges in the navbar, but don't worry I plan to reintegrate them tomorrow.

I also plan to regroup under dropdowns some items in the sidebar.

What do you think?

### CODE REVIEW

**Comment by mohierf** [comment]
Nice job !

Some small remarks: 
- menu items in the sidebar should be a little higher and the sidebar should include the "search hosts" form as in this example :
image

- on lower resolution, the sidebar is not displayed when clicking on the navigation bar button

I will commit few typo modifications early this morning : 
- you still include *ShinkenWebUI.css" that is not useful anymore
- small javascript bug in user's form breaks the layout

**Comment by maethor** [comment]
First, I did'nt want to include ShinkenWebUI.css, my mistake, sorry
about that.

I'm not sure about "search host". I have tested it in the sidebar, and
I prefer it in the navbar-top. 

Moreover, I think we could replace it by the search form of the
problems plugin. What do you think ?

Le 15/06/08 19:59, Frédéric MOHIER claviotta :
> Nice job !
> 
> Some small remarks: 
> - menu items in the sidebar should be a little higher and the sidebar should include the "search hosts" form as in this example :
> image
> 
> - on lower resolution, the sidebar is not displayed when clicking on the navigation bar button
> 
> I will commit few typo modifications early this morning : 
> - you still include *ShinkenWebUI.css" that is not useful anymore
> - small javascript bug in user's form breaks the layout
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/shinken-monitoring/mod-webui/pull/170#issuecomment-110205723

-- 
Guillaume Subiron 
  Mail - maethor@subiron.org
   GPG - 5BC2 EADB
Jabber - maethor@im.subiron.org
   IRC - maethor@(freenode|geeknode)

**Comment by mohierf** [comment]
+1 for the search form of problems page !

**Comment by maethor** [comment]
Great! I'll do this by the end of the day.

**Comment by mohierf** [comment]
Thanks !

2015-06-09 9:42 GMT+02:00 Guillaume Subiron <notifications@github.com>:

**Comment by maethor** [comment]
Hum, the problem' search in the navbar… it's not that simple, because I need to have the bookmarks in every page of the app, not only in the /problems view. I will have to search for the best way to do it in the bottle's documentation.

**Comment by mohierf** [comment]
I find it interesting ... because it will allow to create a dropdown menu with the bookmarks.

Let's imagine a drop down menu including : 
- application bookmarks (the one we pre defined)
- common user's bookmarls (the one an admin is allowed to save as common)
- user's bookmarks (the one saved by the current user)

**Pull request merged**
