### PR TITLE
Close 644 - dashboard widgets selector

### PR DESCRIPTION
**Pull request by mohierf**
Clean the dashboard widgets selector
Add an alias for the widgets rather than using the name

### CODE REVIEW

**Comment by mohierf** [comment]
WiP - I will rebase this PR once #645 will be merged

**Comment by maethor** [comment]
This doesn't work well

2018-11-23-171058_1916x1156_scrot

@mohierf Can you fix it ? If not I will have to revert.

**Comment by mohierf** [comment]
@maethor: what is the problem ? The layout or something else ?

 I tried with Firefox and Chrome ... no problem for me (neither layout nor scripting !):
image


I only noticed a layout problem when hovering the list ... and I will fix this!

**Comment by mohierf** [comment]
See #648 for the widgets selector layout fix

**Pull request merged**
