### PR TITLE
Still some cleanings

### PR DESCRIPTION
**Pull request by mohierf**
Use the WebUI Regenerator class for Shinken objects
Configure Shinken logger in Alignak mode
Add Shinken and Alignak test configurations in the repository (see test/test-configurations)

---
I did a lot of tests with the WebUI + Shinken and WebUI + Alignak ... everything looks fine 😉

### CODE REVIEW

**Comment by maethor** [comment]
It may be a stupid question, don't hesitate to tell me. Should I be concerned about performance and memory consumption?

**Comment by mohierf** [comment]
Performance and memory ? Why this question in relation to this PR ?

**Comment by maethor** [comment]
I don't know :smile:

**Comment by mohierf** [comment]
No matter with this kind of problems. I even think that this new source code will improve the WebUI 😉 

Thanks for merging. I will now rebase my other PRs on the new develop branch ...

**Comment by maethor** [comment]
Wait. It does not work for me, I will have to revert.

**Comment by mohierf** [comment]
What is the problem ?

**Comment by maethor** [comment]
My WebUI does not get the objects. It stays blocked on the first state after restart where it returns a 403 error.

I may have another problem, give me a few minutes.

**Comment by maethor** [comment]
```
1542867910] ERROR: [broker-master] [WebUI] manage_brok_thread exception: Comment instance has no attribute 'uuid'
[1542867910] ERROR: [broker-master] [WebUI] Exception type: <type 'exceptions.AttributeError'>
[1542867910] ERROR: [broker-master] [WebUI] Back trace of this kill: Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui2/module.py", line 630, in manage_brok_thread
    self.rg.manage_brok(b)
  File "/var/lib/shinken/modules/webui2/regenerator.py", line 197, in manage_brok
    return manage(brok)
  File "/var/lib/shinken/modules/webui2/regenerator.py", line 740, in manage_initial_host_status_brok
    comment.id = comment.uuid
AttributeError: Comment instance has no attribute 'uuid'
```

Let me try to fix this.

**Comment by maethor** [comment]
OK I give up, I don't have time to understand what is happening. I'm sorry I have to revert this PR.

**Comment by mohierf** [comment]
I will check this ... whih Shinken version ?

**Comment by mohierf** [comment]
I think I got it!

**Comment by maethor** [comment]
Shinken 2.4.3

**Pull request merged**
