### PR TITLE
[BS3] Various improvements

### PR DESCRIPTION
**Pull request by maethor**
This PR adds some improvements to the BS3 branch, mostly in the problems-table view, but also some debug and a rewrite of the perfometer helper to use bootstrap progress-bars.

### CODE REVIEW

**Comment by maethor** [comment]
@mohierf What do you think ? :)

**Comment by mohierf** [comment]
Nice ! 

 I think that it will be interesting to make it as our default problems view and we should remove the current one?

 I played with this view and noticed some possible improvements : 
- pagination element navigates to */problem* instead of */problems-table*
- problems sorting is quite strange ... see image below
- actions buttons should be present only if needed / allowed (Try to fix only if event handler is defined and enabled ...)
- using an Hand cursor on perfometer is not the best one ...
- we should remove the perfdata (with toto ;-)) from the left toolbar


image

**Comment by maethor** [comment]
I'll submit a new PR today or maybe tomorrow with some new great improvements.

- Yes, all the actions, paginations, etc, are still redirecting to /problems. I can't fix this without modifying the problems.py, and I prefer to avoid doing this because I think this version will soon replace /problems. Are you OK if I switch them in my next PR ?
- Indeed, problem sorting is strange, I didn't think about it, I'll fix it.
- OK for the button actions, I'll see how it's implemented in the master branch.
- I have completely the graph display when overing a performeter, you will see this in the next PR.

Thanks a lot for your comments ! :)

**Comment by mohierf** [comment]
Replies : 
- ok for switching the views in the next PR
- problem sorting is in problems.py, or in regenerator ... to be checked.
- button actions as in eltview, tab Commands ... it will be consistent

**Pull request merged**
