### PR TITLE
Bs3

### PR DESCRIPTION
**Pull request by tarak666**

### CODE REVIEW

**Comment by mohierf** [comment]
Why did you make this PR ? Bad idea ... there are too many differences between these branche !

What is the idea behind this PR ?

**Comment by tarak666** [comment]
Hi, 
Thanks for reply, I have shinken 2.2 installed in centos6. But i don't have history tab in my webui. and downtime issue.

Can you help me out from this two issues.

Thanks,
Tarak

**Comment by mohierf** [comment]
Can you copy/paste a screen capture of your WebUI here ?

**Comment by tarak666** [comment]
Hi,
PFA.. screen capture of my WebUI. 
capture
capture1

**Comment by mohierf** [comment]
The history tab is available in the BS3 WebUI if :
 - you have the livestatus + logstore-mongo broker modules to store the logs
 - you activated the history tab in the WebUI plugin configuration file (plugins/logs/plugin.cfg)

First of all, you need to be sure that your shinken logs are stored in the mongodb database ... and then you will have host/service logs in the history tab.

**Comment by tarak666** [comment]
Hi, 
I have livestatus + logstore-mongo  and activied in broker modules.
I can see log generating in mongo.
{code}
> show databases
local   0.078125GB
shinken 0.203125GB
shinkenLivestatusLogs   0.203125GB
> show tables
> use shinkenLivestatusLogs
switched to db shinkenLivestatusLogs
> db.logs.find()
{ "_id" : ObjectId("000000c04e2870000000b459"), "comment" : "", "plugin_output" : "", "attempt" : 0, "message" : "[111111] PASSIVE SERVICE CHECK: localhost;Check Swap Usage;2;", "logclass" : 4, "options" : "", "state_type" : "", "lineno" : 932, "state" : "2", "host_name" : localhost", "time" : 14111796, "service_description" : "Check Swap Usage", "logobject" : 2, "type" : "PASSIVE SERVICE CHECK", "contact_name" : "", "command_name" : "" }
{code}

But i don't have "plugins/logs/plugin.cfg" file and no ware i see log option on webui.

**Comment by mohierf** [comment]
Are you sure you have BS3 WebUI ? You should have a plugins directory into the WebUI module dir ...

**Comment by tarak666** [comment]
Hi mohierf, 

Sorry for late reply, yes i am using BS3 Webui. I have plugins directory but dont have log directory on it, i have plugin.cfg file on eltdetail directory. And i can see logs in mongodb but i see error " Error : Unable to create mongo DB connection localhost:27017" on webui Log tab.

Thanks,
Tarak

**Comment by mohierf** [comment]
I you have a recent BS3 you should have a logs directory under plugins ... if not, your installation is corrupted.

The error is because the mongodb  server is not launched or your database is not available. Please make sure that : 
- mongodb is running
- logstore-mongodb Shinken module is installed and running
- logstore-mongodb Shinken module database configuration is the same as WebUI (config file in webui/plugins/logs directory)

**Comment by tarak666** [comment]
Yes, I changed code to BS3-1.0 tag, i see lot of chages in webui, Looks great thanks for that.
But No luck on my log and History,
File: Mongodb.cfg
{code}
define module {
    module_name     mongodb
    module_type     mongodb
    uri             mongodb://localhost/?safe=false
    database        shinken
    #username        username     ;optional
    #password        password     ;optional
   }
{code}
file:- logstore_mongodb.cfg
{code}
define module {
    module_name     logstore-mongodb
    module_type     logstore_mongodb
    mongodb_uri     mongodb://localhost/?safe=false  ; Set to your value
    database        shinken
}
{code}
mongod (pid  3024) is running...

And New issue is Graphs, I have Graphite installed and using in shinken2.2.
But now its not showing in details page after changed code.
Screen Shots:-
Graphs tab Missing

History: 

Log


Thanks

**Comment by mohierf** [comment]
I will have a look to your problems on my configuration.

Meanwhile, please open two new issues for that we stop discussing in this PR thread ...

One issue for your mongodb logs problem ...
One issue for your graphite graphs ...

It will be easier to manage.

**Comment by tarak666** [comment]
Sure, Thanks For you help and Time.

**Comment by tarak666** [comment]
https://github.com/shinken-monitoring/mod-graphite/issues/11
https://github.com/shinken-monitoring/mod-logstore-mongodb/issues/12

**Comment by mohierf** [comment]
I close this pull request. Discussion is now in the two opened and referenced issues.

**Pull request closed without merging**
